// Generated by CoffeeScript 1.6.3
(function() {
  var App, chai;

  if (typeof require !== "undefined" && require !== null) {
    App = require('../app/app');
    chai = require('chai');
  } else {
    App = window.App;
  }

  chai.should();

  describe("Application", function() {
    var app;
    app = null;
    return it('should initialize application', function() {
      app = new App;
      return app.should.not.be.undefined;
    });
  });

}).call(this);

/*
//@ sourceMappingURL=app.test.map
*/
