// Generated by CoffeeScript 1.6.3
(function() {
  var App;

  App = (function() {
    function App() {}

    return App;

  })();

  if (typeof module !== "undefined" && module !== null) {
    module.exports = App;
  } else {
    window.App = App;
  }

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
